Neos:
  Flow:
    http:
      chain:
        'process':
          chain:
            'Flownative.Prometheus:metricsExporter':
              'position': 'before routing'
              component: 'Flownative\Prometheus\Http\MetricsExporterComponent'
              componentOptions:

                ## Path at which metrics are published for scraping
                telemetryPath: '/metrics'
