Neos:
  Flow:
    http:
      middlewares:
        'Flownative.Prometheus:metricsExporter':
          'position': 'before routing'
          middleware: 'Flownative\Prometheus\Http\MetricsExporterMiddleware'
