Flownative:
  Prometheus:
    metrics:
      flownative_beach_admin_test_hits_total:
        type: counter
        help: 'A counter for testing'
        labelNames: ['module', 'code']
      flownative_beach_admin_test_temperature:
        type: gauge
        help: 'A test gauge'
